Login Routing & Access
monocliffe/ultimate-blog-project pull request #9
Opened 2020-02-03 12:00 UTC by monocliffe

[TPOZ-1517](https://wpengine.atlassian.net/browse/TPOZ-1517)
[TPOZ-1521](https://wpengine.atlassian.net/browse/TPOZ-1521)
[TPOZ-1522](https://wpengine.atlassian.net/browse/TPOZ-1522)

When requesting a restricted page, specified in the controller, the user is redirected to the login page. After logging in the user is redirected back to the originally requested page.

2020-02-04 15:00 UTC, JamesDominy requested changes

2020-02-04 15:00 UTC, JamesDominy commented on app/controllers/application_controller.rb
> +  #before_action :ensure_login, except: [:index, :new]
Try not to commit commented code ... `git-cola` and `git add -p` are your friends

2020-02-04 15:00 UTC, JamesDominy commented on app/controllers/application_controller.rb
> +    !@current_user.nil?
In general, positive logic assertions are easier to read, e.g. `@current_user.present?`. This is especially true with 'double negatives' arising from assertions about `nil`

2020-02-04 15:00 UTC, JamesDominy commented on app/controllers/application_controller.rb
> +    redirect_to login_path and return false
I don't think you need the `and return` in this case, see https://stackoverflow.com/questions/34842427/redirect-to-vs-redirect-to-and-return

2020-02-04 17:00 UTC, monocliffe commented on app/controllers/application_controller.rb
> +    !@current_user.nil?
Reading back over it, I agree. Changed.

2020-02-04 17:01 UTC, monocliffe commented on app/controllers/application_controller.rb
> +    redirect_to login_path and return false
Also true. Useful to know.

2020-02-04 17:05 UTC, monocliffe commented on app/controllers/application_controller.rb
> +  #before_action :ensure_login, except: [:index, :new]
I'll look into them both. Resources about `git add -p` are kinda sparse, do you have any links?

2020-02-04 17:10 UTC, monocliffe commented on app/controllers/application_controller.rb
> +  #before_action :ensure_login, except: [:index, :new]
I removed the line in this case as it was no longer useful.

2020-02-05 13:43 UTC, JamesDominy approved these changes
👍

2020-02-05 13:45 UTC, merged